name: Build and Test on Linux

on:
  push:
    branches:
      - main
  pull_request_review:
    types: [ submitted ]

jobs:
  build_test_linux:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v4

      - name: Mark Gradle as Executable
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload CLI Jar
        uses: actions/upload-artifact@v5
        with:
          name: jar-builds
          path: build/libs/*.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: linux-builds
          path: build/libs/linux/